export const API_URL = 'https://api.giphy.com/v1/gifs'
export const API_KEY = 'IzXGz27fvHjfGwTEuGtIzVZKw34LTNsy'
//export const API_KEY = 'HkRmTzX5UR0D6Uxa8zZWYum0KNFtnULt'
export const ABOUT= 'about';
export const GIFS= 'gif_home';
export const UPLOAD= 'upload';
export const FAVORITE='favorite';
export const UPLOADED='uploaded';
export const CATS='cats';
export const CONTAINER_SELECTOR= '#container';
